Feat/navigation
vickierose/simple-art-fe pull request #3
Opened 2021-11-18 20:04 UTC by 1Bjorn1

Added routing, some folder architecture, created Header & Home Page

2021-11-19 13:37 UTC, vickierose requested changes

2021-11-19 13:37 UTC, vickierose commented on src/Header/HeaderNav/styles.scss
> +    ul{
don't use tags for styling, use classNames instead

2021-11-19 13:37 UTC, vickierose commented on src/commonComponents/Button/Button.js
> +function Button({name='Apply'}) {
should receive className as well

2021-11-19 13:37 UTC, vickierose commented on src/commonComponents/Button/Button.js
> +        <button className="btn">{name}</button>
className should also be able to apply passed prop. 
therefore it should be a backticked string which firstly has its own classname and after that adds passed classname

2021-11-19 13:37 UTC, vickierose commented on src/Header/styles.scss
> +header {
class, not tag

2021-11-19 13:37 UTC, vickierose commented on src/pages/HomePage/HomePage.js
> +        <main>
this main may go to App.js because it will have same styling on all the pages. use fragment instead

2021-11-19 13:37 UTC, vickierose commented on src/pages/HomePage/styles.scss
> +    font-size: 36px;
this is the case when we can add styles for each header and text into commos file `typography.scss` for example and apply only additional styles.

2021-11-19 13:37 UTC, vickierose commented on src/Header/Header.js
> +           <div><NavLink to="/"><img className="logo" src={Logo} alt="logo" /></NavLink></div>
split the line:
```
<div>
    <NavLink to="/">
        <img className="logo" src={Logo} alt="logo" />
    </NavLink>
</div>
```

2021-11-22 17:01 UTC, 1Bjorn1 commented
fix page & header

2021-11-22 17:03 UTC, 1Bjorn1 commented
fix tasks

2021-11-22 17:04 UTC, vickierose requested changes

2021-11-22 17:04 UTC, vickierose commented on src/commonStyles/variables.scss
> +$button-color: #59ABB0;
no need to duplicate: `$main-theme-color` already has this color

2021-11-22 17:04 UTC, vickierose commented on src/commonStyles/variables.scss
> +$button-text-color: #FFFFFF;
as well: `$white`

2021-11-22 17:23 UTC, merged